version: '3.5'

services:

  proxy:
    build: ./proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - https-reverse-proxy

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - https-reverse-proxy
    depends_on:
      - proxy

volumes:
  certs:
    name: https-reverse-proxy_certs
  vhost.d:
    name: https-reverse-proxy_vhost.d
  html:
    name: https-reverse-proxy_html

networks:
  https-reverse-proxy:
    driver: bridge
    name: https-reverse-proxy
