version: '3.5'

services:

  web:
    image: nginx
    container_name: simple-example
    restart: always
    environment:
      - VIRTUAL_HOST=nginx.<mydomain.com>
      - LETSENCRYPT_HOST=nginx.<mydomain.com>
      - LETSENCRYPT_EMAIL=<email>
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external:
      name: https-reverse-proxy
 
